platform :ios, '7.0'

pod '500px-iOS-api', '~> 1.0.5'
pod 'MMPReactiveStompClient', '~> 0.1.0'
pod 'AsyncImageDownloader', '~> 1.0.0'

target :unit_tests, :exclusive => true do
  link_with 'UnitTests'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
  pod 'OHHTTPStubs'
end

